"""add_step_constraints_and_unique_index

Revision ID: 9e35486cd757
Revises: bec1d037cc90
Create Date: 2026-01-22 00:47:21.327853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e35486cd757'
down_revision: Union[str, Sequence[str], None] = 'bec1d037cc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_steps_run_id_index_notnull', 'steps', ['run_id', 'index'], unique=True, postgresql_where=sa.text('run_id IS NOT NULL'))
    op.drop_constraint(op.f('steps_run_id_fkey'), 'steps', type_='foreignkey')
    op.create_foreign_key(None, 'steps', 'runs', ['run_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'steps', type_='foreignkey')
    op.create_foreign_key(op.f('steps_run_id_fkey'), 'steps', 'runs', ['run_id'], ['id'])
    op.drop_index('uq_steps_run_id_index_notnull', table_name='steps', postgresql_where=sa.text('run_id IS NOT NULL'))
    # ### end Alembic commands ###
