"""unique_run_validation_input_hash

Revision ID: a19960b6fae8
Revises: 4faf3251f5cc
Create Date: 2026-01-23 06:28:03.877941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19960b6fae8'
down_revision: Union[str, Sequence[str], None] = '4faf3251f5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_run_validations_input_hash'), 'run_validations', ['input_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_validations_input_hash'), table_name='run_validations')
    # ### end Alembic commands ###
