"""nullable_step_run_id

Revision ID: bec1d037cc90
Revises: 2e749a281ce0
Create Date: 2025-12-22 14:37:17.590000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec1d037cc90'
down_revision: Union[str, Sequence[str], None] = '2e749a281ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steps', 'run_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steps', 'run_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
