"""add_run_validations

Revision ID: cedb180ba24d
Revises: e57d3c71eb14
Create Date: 2026-01-22 21:18:22.955761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cedb180ba24d'
down_revision: Union[str, Sequence[str], None] = 'e57d3c71eb14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('runbook_yaml', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_validations_created_at'), 'run_validations', ['created_at'], unique=False)
    op.create_index(op.f('ix_run_validations_run_id'), 'run_validations', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_validations_status'), 'run_validations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_validations_status'), table_name='run_validations')
    op.drop_index(op.f('ix_run_validations_run_id'), table_name='run_validations')
    op.drop_index(op.f('ix_run_validations_created_at'), table_name='run_validations')
    op.drop_table('run_validations')
    # ### end Alembic commands ###
